### PR TITLE
SET-16 removed activated services tab

### PR DESCRIPTION
**Pull request by doubleface**

### CODE REVIEW

**Comment by GoOz** [comment]
Is this view removed FOR EVER AND EVER? 😮 

Not totally sure about `.set-table-status`. Just check what the table in the device view needs and remove the unused.

**Comment by doubleface** [comment]
@GoOz This view is removed from the code but this commit will get a tag so we can get back to it when needed.

And OK I will check what is needed with the device view

**Comment by gregorylegarec** [comment]
@GoOz already checked, everything will be ok. I think.

**Comment by gregorylegarec** [comment]
Thanks @doubleface ! 👍

**Pull request merged**
