### PR TITLE
Remove useless close button from intent support view

### PR DESCRIPTION
**Pull request by CPatchane**

### CODE REVIEW

**Comment by CPatchane** [comment]
[(5) [BAR-18] Bouton d'aide : envoi d'un mail](https://trello.com/c/FHb89K5i/617-5-bar-18-bouton-daide-envoi-dun-mail)

**Comment by gregorylegarec** [comment]
Is it ready to merge ? May you remove the `WIP` when it's ok ? Thanks :)

**Comment by CPatchane** [comment]
Oops, sorry, it's done :)

**Comment by gregorylegarec** [comment]
NP @CPatchane, thanks ! 🖌

**Pull request merged**
