### PR TITLE
Fix delete account

### PR DESCRIPTION
**Pull request by CPatchane**
We don't need to have context here for the domain any more and it wasn't working since a while.

### CODE REVIEW

**Comment by CPatchane** [comment]
[🔵 🍊 [SET] Perte du domain à l'envoie de la demande de suppression](https://trello.com/c/qBYZRjgN/1485-%F0%9F%94%B5-%F0%9F%8D%8A-set-perte-du-domain-%C3%A0-lenvoie-de-la-demande-de-suppression)

**Comment by edas** [comment]
Could you add a test ?

**Comment by CPatchane** [comment]
I changed to make the FormModal reading directly the domain from the HTML page and remove the props passing here. Do you see a good way to test this case efficiently @edas?

**Comment by edas** [comment]
> I changed to make the FormModal reading directly the domain from the HTML page and remove the props passing here. Do you see a good way to test this case efficiently @edas?

You can 
- inject a fake HTML document with jest
- mock `sendDeleteAccountRequest`

Then 
- check that sendDeleteAccountRequest subject does contain the domain
- check that sendDeleteAccountRequest subject does not contain %{domain}

**Pull request merged**
